#!/bin/bash

ssh_user=jfb
ssh_host=127.0.0.1
ssh_port=10022
# Driver for mk-patch.py, which is run from INSIDE of the builder VM.

if [ -z "$1" -o -z "$2" ]; then
    echo "usage: $0 from-exe to-exe"
    exit 1
fi

from=$1
to=$2


#kvm -m 4G -net nic,model=rtl8139 -net user,hostfwd=tcp:127.0.0.1:10022-:22 -drive file=/opt/prereq-win-aio.qcow2,snapshot=on -nographic &
#kvm -m 6G -smp 2 -cpu host -machine accel=kvm -net nic,model=rtl8139 -net user,hostfwd=tcp:127.0.0.1:10022-:22 -
#kvm -m 6G -net nic,model=rtl8139 -cpu max -smp 2 -machine accel=kvm -net user,hostfwd=tcp:127.0.0.1:10022-:22 -drive file=/opt/prereq-py3.10-win-aio.qcow2,if=virtio,snapshot=on &
#kvm -m 6G -net nic,model=rtl8139 -cpu max -smp 2 -machine accel=kvm -net user,hostfwd=tcp:127.0.0.1:10022-:22 -drive file=/opt/prereq-win-aio.qcow2,if=virtio,snapshot=on &
#kvm -m 10G -net nic,model=virtio -smp 8 -machine accel=kvm -net user,hostfwd=tcp:127.0.0.1:10022-:22 -drive file=/opt/prereq-win-aio.qcow2,if=virtio,snapshot=on &
kvm -m 10G -net nic,model=virtio -smp 8 -machine accel=kvm -net user,hostfwd=tcp:127.0.0.1:10022-:22 -drive file=/home/jf/Virt/prereq-py3.10-win-aio.qcow2,if=virtio,snapshot=on &
pid=$!
sleep 10


ssh_args="-p $ssh_port $ssh_user@$ssh_host"
ssh $ssh_args -- net stop Postgres /y
ssh $ssh_args -- rm -fr /cygdrive/c/to_db/
ssh $ssh_args -- rm -fr "/cygdrive/c/Program\ Files\ \(x86\)/msf"

# Put the script and the two files on the VM
echo "Copying the files over to the VM."
scp -P $ssh_port mk-patch.py \
    $from $to \
    $ssh_user@$ssh_host:

from=`basename $from`
to=`basename $to`

split_to=(${to//-/ })
version=${split_to[3]}
echo ssh $ssh_args chmod +x $from $fo
ssh $ssh_args chmod +x $from $fo


echo ssh $ssh_args WPy64-310111/python-3.10.11.amd64/python.exe  mk-patch.py $from $to
ssh $ssh_args WPy64-310111/python-3.10.11.amd64/python.exe mk-patch.py $from $to

rm -f ${version}.patch.zip
echo scp -P $ssh_port $ssh_user@$ssh_host:patch.zip ${version}.patch.zip
scp -P $ssh_port $ssh_user@$ssh_host:patch.zip ${version}.patch.zip


echo 
echo "The new patch is in patch.zip. Rename it as desired."
ls -l ${version}.patch.zip
md5sum ${version}.patch.zip

kill -9 $pid
