#!/bin/sh

# Prefer c:\Python27 over the Python stuff from Cygwin
#PATH=/cygdrive/c/Python27/Scripts:/cygdrive/c/Python27:$PATH
#export PATH

set -x -e

# The VC Redist for VC2008, required for Python on the
# WinXP builder machine.
chmod +x lib/vcredist_x86.exe
./lib/vcredist_x86.exe /q

#wget https://github.com/winpython/winpython/releases/download/4.6.20220116/Winpython64-3.10.2.0dot.exe
#chmod +x Winpython64-3.10.2.0dot.exe
#./Winpython64-3.10.2.0dot.exe  -y -gm2 -InstallPath="."
#rm -fr Winpython64-3.10.2.0dot.exe

#wget https://github.com/winpython/winpython/releases/download/4.3.20210620/Winpython64-3.8.10.0dot.exe
wget https://github.com/winpython/winpython/releases/download/6.1.20230527/Winpython64-3.10.11.1dot.exe
chmod +x Winpython64-3.10.11.1dot.exe
./Winpython64-3.10.11.1dot.exe -y -gm2 -InstallPath="."
rm -fr Winpython64-3.10.11.1dot.exe
# => python is in WPy64-310111/python-3.10.11.amd64/

wget https://aka.ms/nugetclidl
chmod +x nugetclidl
./nugetclidl install python -Version 3.12.9 -OutputDirectory .
mv python.3.12.9/tools/ python-3.12.9


# Python
#rm -f python-2.7.13.msi
#wget https://www.python.org/ftp/python/2.7.13/python-2.7.13.msi
#msiexec.exe /qn /i python-2.7.13.msi
#rm -f python-2.7.13.msi

# PIP
#rm -f get-pip.py
#wget https://bootstrap.pypa.io/get-pip.py
#python get-pip.py
#rm -f get-pip.py

# Now install the pre-reqs to being able to load UF's setup.py
# These should be listed in the setup_requires, see:
# https://pip.readthedocs.io/en/1.4.1/cookbook.html
#pip install py2exe_py2==0.6.9 pytz==2017.2

# Install the packages which are not installable via "pip install"
# and instead have to come from a .whl file.
#pip install lib/whl/*
#for i in lib/exe/*
#do
#	easy_install $i
#done

#rm -rf lib

wget https://sourceforge.net/projects/nsis/files/NSIS%203/3.06.1/nsis-3.06.1.zip
unzip -o nsis-3.06.1.zip
chmod +x nsis-3.06.1/*.exe nsis-3.06.1/Bin/*

mkdir s
cd s
wget https://nsis.sourceforge.io/mediawiki/images/e/ef/NSIS_Simple_Service_Plugin_Unicode_1.30.zip
unzip NSIS_Simple_Service_Plugin_Unicode_1.30.zip
mv SimpleSC.dll ../nsis-3.06.1/Plugins/x86-unicode/
cd ..
rm -rf s

rm uf-prereq

# Now shut down the server
shutdown -s -t 0
