#Listen @@APACHEPORT@@
<VirtualHost *:@@APACHEPORT@@>
    ProxyRequests Off
    ProxyPreserveHost On
    ServerName @@APACHEHOST@@.dsp.uf3.unifield.org

    ProxyPass /  http://localhost:@@WEBPORT@@/
        
    # Fix IE problem (http error 408/409)
    SetEnv proxy-nokeepalive 1

    ErrorLog /var/log/apache2/@@USERERP@@-error.log
    CustomLog /var/log/apache2/@@USERERP@@-access.log common

   <Proxy *>
     Order deny,allow
     Allow from all
   </Proxy>
</VirtualHost>
<VirtualHost *:80>
  ServerName @@APACHEHOST@@_dump.dsp.uf3.unifield.org   
  DocumentRoot /home/@@USERERP@@/exports/
   <Directory /home/@@USERERP@@/exports/>
	Options Indexes
	IndexOrderDefault Descending Date
	AllowOverride None
	Order allow,deny
	allow from all
   </Directory>
</VirtualHost>
