#!/bin/sh

### BEGIN INIT INFO
# Provides:		openerp-server
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Should-Start:		$network
# Should-Stop:		$network
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Enterprise Resource Management software
# Description:		Open ERP is a complete ERP and CRM software.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=@@USERERP_HOME@@/unifield-server/bin/openerp-server.py
NAME=openerp-server-@@USERERP@@
DESC=openerp-server-@@USERERP@@

USER=@@USERERP@@

LOG=@@USERERP_HOME@@/log/openerp-server.log
CONFIG=@@USERERP_HOME@@/etc/openerprc
PIDFILE=@@USERERP_HOME@@/etc/openerp-server.pid
test -x ${DAEMON} || exit 0

set -e

case "${1}" in
	start)
		echo -n "Starting ${DESC}: "
		touch ${PIDFILE}
		start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
			--chuid ${USER} --background --make-pidfile \
			--exec ${DAEMON} -- --config=${CONFIG} \
			    --logfile=${LOG}
		chown $USER $PIDFILE
		echo "${NAME}."
		;;

	stop)
		echo -n "Stopping ${DESC}: "

		start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
			--oknodo

		echo "${NAME}."
		;;

	restart|force-reload)
		echo -n "Restarting ${DESC}: "

		start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
			--oknodo

		sleep 1

		start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
			--chuid ${USER} --background --make-pidfile \
			--exec ${DAEMON} -- --config=${CONFIG} \
			    --logfile=${LOG}

		chown $USER $PIDFILE
		echo "${NAME}."
		;;

	*)
		N=/etc/init.d/${NAME}
		echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0
